package cn.com.fangself.dao;

import cn.com.fangself.model.pojo.Customer;
import cn.com.fangself.model.pojo.CustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    long countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer customerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    Customer selectByPrimaryKey(Integer customerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int updateByPrimaryKey(Customer record);
}