package cn.com.fangself.dao;

import cn.com.fangself.model.pojo.Manager;
import cn.com.fangself.model.pojo.ManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    long countByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int deleteByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer managerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int insertSelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    List<Manager> selectByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    Manager selectByPrimaryKey(Integer managerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") Manager record, @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int updateByExample(@Param("record") Manager record, @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    int updateByPrimaryKey(Manager record);
}