package cn.com.fangself.model.pojo;

import java.util.ArrayList;
import java.util.List;

import org.springframework.context.annotation.ComponentScan;

@ComponentScan

public class ClientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public ClientExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClientidIsNull() {
            addCriterion("clientid is null");
            return (Criteria) this;
        }

        public Criteria andClientidIsNotNull() {
            addCriterion("clientid is not null");
            return (Criteria) this;
        }

        public Criteria andClientidEqualTo(Integer value) {
            addCriterion("clientid =", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotEqualTo(Integer value) {
            addCriterion("clientid <>", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidGreaterThan(Integer value) {
            addCriterion("clientid >", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidGreaterThanOrEqualTo(Integer value) {
            addCriterion("clientid >=", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidLessThan(Integer value) {
            addCriterion("clientid <", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidLessThanOrEqualTo(Integer value) {
            addCriterion("clientid <=", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidIn(List<Integer> values) {
            addCriterion("clientid in", values, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotIn(List<Integer> values) {
            addCriterion("clientid not in", values, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidBetween(Integer value1, Integer value2) {
            addCriterion("clientid between", value1, value2, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotBetween(Integer value1, Integer value2) {
            addCriterion("clientid not between", value1, value2, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientuuidIsNull() {
            addCriterion("clientuuid is null");
            return (Criteria) this;
        }

        public Criteria andClientuuidIsNotNull() {
            addCriterion("clientuuid is not null");
            return (Criteria) this;
        }

        public Criteria andClientuuidEqualTo(String value) {
            addCriterion("clientuuid =", value, "clientuuid");
            return (Criteria) this;
        }

        public Criteria andClientuuidNotEqualTo(String value) {
            addCriterion("clientuuid <>", value, "clientuuid");
            return (Criteria) this;
        }

        public Criteria andClientuuidGreaterThan(String value) {
            addCriterion("clientuuid >", value, "clientuuid");
            return (Criteria) this;
        }

        public Criteria andClientuuidGreaterThanOrEqualTo(String value) {
            addCriterion("clientuuid >=", value, "clientuuid");
            return (Criteria) this;
        }

        public Criteria andClientuuidLessThan(String value) {
            addCriterion("clientuuid <", value, "clientuuid");
            return (Criteria) this;
        }

        public Criteria andClientuuidLessThanOrEqualTo(String value) {
            addCriterion("clientuuid <=", value, "clientuuid");
            return (Criteria) this;
        }

        public Criteria andClientuuidLike(String value) {
            addCriterion("clientuuid like", value, "clientuuid");
            return (Criteria) this;
        }

        public Criteria andClientuuidNotLike(String value) {
            addCriterion("clientuuid not like", value, "clientuuid");
            return (Criteria) this;
        }

        public Criteria andClientuuidIn(List<String> values) {
            addCriterion("clientuuid in", values, "clientuuid");
            return (Criteria) this;
        }

        public Criteria andClientuuidNotIn(List<String> values) {
            addCriterion("clientuuid not in", values, "clientuuid");
            return (Criteria) this;
        }

        public Criteria andClientuuidBetween(String value1, String value2) {
            addCriterion("clientuuid between", value1, value2, "clientuuid");
            return (Criteria) this;
        }

        public Criteria andClientuuidNotBetween(String value1, String value2) {
            addCriterion("clientuuid not between", value1, value2, "clientuuid");
            return (Criteria) this;
        }

        public Criteria andMangeridIsNull() {
            addCriterion("mangerid is null");
            return (Criteria) this;
        }

        public Criteria andMangeridIsNotNull() {
            addCriterion("mangerid is not null");
            return (Criteria) this;
        }

        public Criteria andMangeridEqualTo(Integer value) {
            addCriterion("mangerid =", value, "mangerid");
            return (Criteria) this;
        }

        public Criteria andMangeridNotEqualTo(Integer value) {
            addCriterion("mangerid <>", value, "mangerid");
            return (Criteria) this;
        }

        public Criteria andMangeridGreaterThan(Integer value) {
            addCriterion("mangerid >", value, "mangerid");
            return (Criteria) this;
        }

        public Criteria andMangeridGreaterThanOrEqualTo(Integer value) {
            addCriterion("mangerid >=", value, "mangerid");
            return (Criteria) this;
        }

        public Criteria andMangeridLessThan(Integer value) {
            addCriterion("mangerid <", value, "mangerid");
            return (Criteria) this;
        }

        public Criteria andMangeridLessThanOrEqualTo(Integer value) {
            addCriterion("mangerid <=", value, "mangerid");
            return (Criteria) this;
        }

        public Criteria andMangeridIn(List<Integer> values) {
            addCriterion("mangerid in", values, "mangerid");
            return (Criteria) this;
        }

        public Criteria andMangeridNotIn(List<Integer> values) {
            addCriterion("mangerid not in", values, "mangerid");
            return (Criteria) this;
        }

        public Criteria andMangeridBetween(Integer value1, Integer value2) {
            addCriterion("mangerid between", value1, value2, "mangerid");
            return (Criteria) this;
        }

        public Criteria andMangeridNotBetween(Integer value1, Integer value2) {
            addCriterion("mangerid not between", value1, value2, "mangerid");
            return (Criteria) this;
        }

        public Criteria andClientnameIsNull() {
            addCriterion("clientname is null");
            return (Criteria) this;
        }

        public Criteria andClientnameIsNotNull() {
            addCriterion("clientname is not null");
            return (Criteria) this;
        }

        public Criteria andClientnameEqualTo(String value) {
            addCriterion("clientname =", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameNotEqualTo(String value) {
            addCriterion("clientname <>", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameGreaterThan(String value) {
            addCriterion("clientname >", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameGreaterThanOrEqualTo(String value) {
            addCriterion("clientname >=", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameLessThan(String value) {
            addCriterion("clientname <", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameLessThanOrEqualTo(String value) {
            addCriterion("clientname <=", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameLike(String value) {
            addCriterion("clientname like", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameNotLike(String value) {
            addCriterion("clientname not like", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameIn(List<String> values) {
            addCriterion("clientname in", values, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameNotIn(List<String> values) {
            addCriterion("clientname not in", values, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameBetween(String value1, String value2) {
            addCriterion("clientname between", value1, value2, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameNotBetween(String value1, String value2) {
            addCriterion("clientname not between", value1, value2, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientpwdIsNull() {
            addCriterion("clientpwd is null");
            return (Criteria) this;
        }

        public Criteria andClientpwdIsNotNull() {
            addCriterion("clientpwd is not null");
            return (Criteria) this;
        }

        public Criteria andClientpwdEqualTo(String value) {
            addCriterion("clientpwd =", value, "clientpwd");
            return (Criteria) this;
        }

        public Criteria andClientpwdNotEqualTo(String value) {
            addCriterion("clientpwd <>", value, "clientpwd");
            return (Criteria) this;
        }

        public Criteria andClientpwdGreaterThan(String value) {
            addCriterion("clientpwd >", value, "clientpwd");
            return (Criteria) this;
        }

        public Criteria andClientpwdGreaterThanOrEqualTo(String value) {
            addCriterion("clientpwd >=", value, "clientpwd");
            return (Criteria) this;
        }

        public Criteria andClientpwdLessThan(String value) {
            addCriterion("clientpwd <", value, "clientpwd");
            return (Criteria) this;
        }

        public Criteria andClientpwdLessThanOrEqualTo(String value) {
            addCriterion("clientpwd <=", value, "clientpwd");
            return (Criteria) this;
        }

        public Criteria andClientpwdLike(String value) {
            addCriterion("clientpwd like", value, "clientpwd");
            return (Criteria) this;
        }

        public Criteria andClientpwdNotLike(String value) {
            addCriterion("clientpwd not like", value, "clientpwd");
            return (Criteria) this;
        }

        public Criteria andClientpwdIn(List<String> values) {
            addCriterion("clientpwd in", values, "clientpwd");
            return (Criteria) this;
        }

        public Criteria andClientpwdNotIn(List<String> values) {
            addCriterion("clientpwd not in", values, "clientpwd");
            return (Criteria) this;
        }

        public Criteria andClientpwdBetween(String value1, String value2) {
            addCriterion("clientpwd between", value1, value2, "clientpwd");
            return (Criteria) this;
        }

        public Criteria andClientpwdNotBetween(String value1, String value2) {
            addCriterion("clientpwd not between", value1, value2, "clientpwd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_client
     *
     * @mbg.generated do_not_delete_during_merge Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_client
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}