package cn.com.fangself.model.pojo;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_client.clientid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    private Integer clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_client.clientuuid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    private String clientuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_client.mangerid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    private Integer mangerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_client.clientname
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    private String clientname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_client.clientpwd
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    private String clientpwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_client.clientid
     *
     * @return the value of tb_client.clientid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_client.clientid
     *
     * @param clientid the value for tb_client.clientid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_client.clientuuid
     *
     * @return the value of tb_client.clientuuid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public String getClientuuid() {
        return clientuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_client.clientuuid
     *
     * @param clientuuid the value for tb_client.clientuuid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setClientuuid(String clientuuid) {
        this.clientuuid = clientuuid == null ? null : clientuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_client.mangerid
     *
     * @return the value of tb_client.mangerid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public Integer getMangerid() {
        return mangerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_client.mangerid
     *
     * @param mangerid the value for tb_client.mangerid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setMangerid(Integer mangerid) {
        this.mangerid = mangerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_client.clientname
     *
     * @return the value of tb_client.clientname
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public String getClientname() {
        return clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_client.clientname
     *
     * @param clientname the value for tb_client.clientname
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setClientname(String clientname) {
        this.clientname = clientname == null ? null : clientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_client.clientpwd
     *
     * @return the value of tb_client.clientpwd
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public String getClientpwd() {
        return clientpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_client.clientpwd
     *
     * @param clientpwd the value for tb_client.clientpwd
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setClientpwd(String clientpwd) {
        this.clientpwd = clientpwd == null ? null : clientpwd.trim();
    }
}