package cn.com.fangself.model.pojo;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.customerid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    private Integer customerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.customeruuid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    private String customeruuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.customername
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    private String customername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.customerpwd
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    private String customerpwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.customerid
     *
     * @return the value of tb_customer.customerid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.customerid
     *
     * @param customerid the value for tb_customer.customerid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.customeruuid
     *
     * @return the value of tb_customer.customeruuid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public String getCustomeruuid() {
        return customeruuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.customeruuid
     *
     * @param customeruuid the value for tb_customer.customeruuid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setCustomeruuid(String customeruuid) {
        this.customeruuid = customeruuid == null ? null : customeruuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.customername
     *
     * @return the value of tb_customer.customername
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.customername
     *
     * @param customername the value for tb_customer.customername
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.customerpwd
     *
     * @return the value of tb_customer.customerpwd
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public String getCustomerpwd() {
        return customerpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.customerpwd
     *
     * @param customerpwd the value for tb_customer.customerpwd
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setCustomerpwd(String customerpwd) {
        this.customerpwd = customerpwd == null ? null : customerpwd.trim();
    }
}