package cn.com.fangself.model.pojo;

import java.util.ArrayList;
import java.util.List;

public class ManagerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public ManagerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andManageridIsNull() {
            addCriterion("managerid is null");
            return (Criteria) this;
        }

        public Criteria andManageridIsNotNull() {
            addCriterion("managerid is not null");
            return (Criteria) this;
        }

        public Criteria andManageridEqualTo(Integer value) {
            addCriterion("managerid =", value, "managerid");
            return (Criteria) this;
        }

        public Criteria andManageridNotEqualTo(Integer value) {
            addCriterion("managerid <>", value, "managerid");
            return (Criteria) this;
        }

        public Criteria andManageridGreaterThan(Integer value) {
            addCriterion("managerid >", value, "managerid");
            return (Criteria) this;
        }

        public Criteria andManageridGreaterThanOrEqualTo(Integer value) {
            addCriterion("managerid >=", value, "managerid");
            return (Criteria) this;
        }

        public Criteria andManageridLessThan(Integer value) {
            addCriterion("managerid <", value, "managerid");
            return (Criteria) this;
        }

        public Criteria andManageridLessThanOrEqualTo(Integer value) {
            addCriterion("managerid <=", value, "managerid");
            return (Criteria) this;
        }

        public Criteria andManageridIn(List<Integer> values) {
            addCriterion("managerid in", values, "managerid");
            return (Criteria) this;
        }

        public Criteria andManageridNotIn(List<Integer> values) {
            addCriterion("managerid not in", values, "managerid");
            return (Criteria) this;
        }

        public Criteria andManageridBetween(Integer value1, Integer value2) {
            addCriterion("managerid between", value1, value2, "managerid");
            return (Criteria) this;
        }

        public Criteria andManageridNotBetween(Integer value1, Integer value2) {
            addCriterion("managerid not between", value1, value2, "managerid");
            return (Criteria) this;
        }

        public Criteria andManageruuidIsNull() {
            addCriterion("manageruuid is null");
            return (Criteria) this;
        }

        public Criteria andManageruuidIsNotNull() {
            addCriterion("manageruuid is not null");
            return (Criteria) this;
        }

        public Criteria andManageruuidEqualTo(String value) {
            addCriterion("manageruuid =", value, "manageruuid");
            return (Criteria) this;
        }

        public Criteria andManageruuidNotEqualTo(String value) {
            addCriterion("manageruuid <>", value, "manageruuid");
            return (Criteria) this;
        }

        public Criteria andManageruuidGreaterThan(String value) {
            addCriterion("manageruuid >", value, "manageruuid");
            return (Criteria) this;
        }

        public Criteria andManageruuidGreaterThanOrEqualTo(String value) {
            addCriterion("manageruuid >=", value, "manageruuid");
            return (Criteria) this;
        }

        public Criteria andManageruuidLessThan(String value) {
            addCriterion("manageruuid <", value, "manageruuid");
            return (Criteria) this;
        }

        public Criteria andManageruuidLessThanOrEqualTo(String value) {
            addCriterion("manageruuid <=", value, "manageruuid");
            return (Criteria) this;
        }

        public Criteria andManageruuidLike(String value) {
            addCriterion("manageruuid like", value, "manageruuid");
            return (Criteria) this;
        }

        public Criteria andManageruuidNotLike(String value) {
            addCriterion("manageruuid not like", value, "manageruuid");
            return (Criteria) this;
        }

        public Criteria andManageruuidIn(List<String> values) {
            addCriterion("manageruuid in", values, "manageruuid");
            return (Criteria) this;
        }

        public Criteria andManageruuidNotIn(List<String> values) {
            addCriterion("manageruuid not in", values, "manageruuid");
            return (Criteria) this;
        }

        public Criteria andManageruuidBetween(String value1, String value2) {
            addCriterion("manageruuid between", value1, value2, "manageruuid");
            return (Criteria) this;
        }

        public Criteria andManageruuidNotBetween(String value1, String value2) {
            addCriterion("manageruuid not between", value1, value2, "manageruuid");
            return (Criteria) this;
        }

        public Criteria andManagernameIsNull() {
            addCriterion("managername is null");
            return (Criteria) this;
        }

        public Criteria andManagernameIsNotNull() {
            addCriterion("managername is not null");
            return (Criteria) this;
        }

        public Criteria andManagernameEqualTo(String value) {
            addCriterion("managername =", value, "managername");
            return (Criteria) this;
        }

        public Criteria andManagernameNotEqualTo(String value) {
            addCriterion("managername <>", value, "managername");
            return (Criteria) this;
        }

        public Criteria andManagernameGreaterThan(String value) {
            addCriterion("managername >", value, "managername");
            return (Criteria) this;
        }

        public Criteria andManagernameGreaterThanOrEqualTo(String value) {
            addCriterion("managername >=", value, "managername");
            return (Criteria) this;
        }

        public Criteria andManagernameLessThan(String value) {
            addCriterion("managername <", value, "managername");
            return (Criteria) this;
        }

        public Criteria andManagernameLessThanOrEqualTo(String value) {
            addCriterion("managername <=", value, "managername");
            return (Criteria) this;
        }

        public Criteria andManagernameLike(String value) {
            addCriterion("managername like", value, "managername");
            return (Criteria) this;
        }

        public Criteria andManagernameNotLike(String value) {
            addCriterion("managername not like", value, "managername");
            return (Criteria) this;
        }

        public Criteria andManagernameIn(List<String> values) {
            addCriterion("managername in", values, "managername");
            return (Criteria) this;
        }

        public Criteria andManagernameNotIn(List<String> values) {
            addCriterion("managername not in", values, "managername");
            return (Criteria) this;
        }

        public Criteria andManagernameBetween(String value1, String value2) {
            addCriterion("managername between", value1, value2, "managername");
            return (Criteria) this;
        }

        public Criteria andManagernameNotBetween(String value1, String value2) {
            addCriterion("managername not between", value1, value2, "managername");
            return (Criteria) this;
        }

        public Criteria andManagerpwdIsNull() {
            addCriterion("managerpwd is null");
            return (Criteria) this;
        }

        public Criteria andManagerpwdIsNotNull() {
            addCriterion("managerpwd is not null");
            return (Criteria) this;
        }

        public Criteria andManagerpwdEqualTo(String value) {
            addCriterion("managerpwd =", value, "managerpwd");
            return (Criteria) this;
        }

        public Criteria andManagerpwdNotEqualTo(String value) {
            addCriterion("managerpwd <>", value, "managerpwd");
            return (Criteria) this;
        }

        public Criteria andManagerpwdGreaterThan(String value) {
            addCriterion("managerpwd >", value, "managerpwd");
            return (Criteria) this;
        }

        public Criteria andManagerpwdGreaterThanOrEqualTo(String value) {
            addCriterion("managerpwd >=", value, "managerpwd");
            return (Criteria) this;
        }

        public Criteria andManagerpwdLessThan(String value) {
            addCriterion("managerpwd <", value, "managerpwd");
            return (Criteria) this;
        }

        public Criteria andManagerpwdLessThanOrEqualTo(String value) {
            addCriterion("managerpwd <=", value, "managerpwd");
            return (Criteria) this;
        }

        public Criteria andManagerpwdLike(String value) {
            addCriterion("managerpwd like", value, "managerpwd");
            return (Criteria) this;
        }

        public Criteria andManagerpwdNotLike(String value) {
            addCriterion("managerpwd not like", value, "managerpwd");
            return (Criteria) this;
        }

        public Criteria andManagerpwdIn(List<String> values) {
            addCriterion("managerpwd in", values, "managerpwd");
            return (Criteria) this;
        }

        public Criteria andManagerpwdNotIn(List<String> values) {
            addCriterion("managerpwd not in", values, "managerpwd");
            return (Criteria) this;
        }

        public Criteria andManagerpwdBetween(String value1, String value2) {
            addCriterion("managerpwd between", value1, value2, "managerpwd");
            return (Criteria) this;
        }

        public Criteria andManagerpwdNotBetween(String value1, String value2) {
            addCriterion("managerpwd not between", value1, value2, "managerpwd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_manager
     *
     * @mbg.generated do_not_delete_during_merge Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_manager
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}