package cn.com.fangself.model.pojo;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.managerid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    private Integer managerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.manageruuid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    private String manageruuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.managername
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    private String managername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.managerpwd
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    private String managerpwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.managerid
     *
     * @return the value of tb_manager.managerid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.managerid
     *
     * @param managerid the value for tb_manager.managerid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.manageruuid
     *
     * @return the value of tb_manager.manageruuid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public String getManageruuid() {
        return manageruuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.manageruuid
     *
     * @param manageruuid the value for tb_manager.manageruuid
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setManageruuid(String manageruuid) {
        this.manageruuid = manageruuid == null ? null : manageruuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.managername
     *
     * @return the value of tb_manager.managername
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public String getManagername() {
        return managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.managername
     *
     * @param managername the value for tb_manager.managername
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setManagername(String managername) {
        this.managername = managername == null ? null : managername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.managerpwd
     *
     * @return the value of tb_manager.managerpwd
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public String getManagerpwd() {
        return managerpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.managerpwd
     *
     * @param managerpwd the value for tb_manager.managerpwd
     *
     * @mbg.generated Sun Jun 04 21:02:56 GMT+08:00 2017
     */
    public void setManagerpwd(String managerpwd) {
        this.managerpwd = managerpwd == null ? null : managerpwd.trim();
    }
}